import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Logout from "./(logout)/Logout";
import { AuthProvider } from "./provider/AuthProvider";
import Nav from "./Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="w-full grid place-items-center bg-slate-900">
            <Nav />
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
